### ISSUE TITLE
Syntax highlighting for `utop`.

### ISSUE THREAD

**Issue by genkimarshall** [cs3110/vagrant-opam#2]
It might be cool to give students syntax highlighting for `utop`.
This can be done by running the command:
```bash
$ curl -o ~/.utoprc https://raw.githubusercontent.com/diml/utop/master/utoprc-dark
```
See [the `utop` repo](https://github.com/diml/utop#colors) for more details.

**Comment by remyjette** [comment]
Wow, I was almost certain we had a `.utoprc` in https://github.com/cs3110/tools/tree/master/config - but we don't.

I certainly wouldn't be opposed to adding one.

**Comment by genkimarshall** [comment]
Alright, shall I submit a pull request?
I was thinking I could add that `curl` command into [here](https://github.com/cs3110/vagrant-opam/blob/master/setup-opam.sh) at the end, or add a new `setup-utop.sh` script, and add it to be called [here](https://github.com/cs3110/vagrant-opam/blob/master/Vagrantfile) after `setup-opam.sh`.
Thoughts?

**Comment by remyjette** [comment]
Actually, I think rather than doing an unnecessary `curl` call, we should define our own `.utoprc` file and to start with populate it with the values from utop-dark (we don't need to copy the comments from that file).

That is, add a file `utoprc` (no leading dot) to https://github.com/cs3110/tools/tree/master/config, then add the line

    cp 3110-tools/config/utoprc ~/.utoprc

to `setup-opam.sh`. (see the `vimrc` file in the `tools/config` directory and the `setup-vim.sh` script).

**Comment by genkimarshall** [comment]
Alright, submitted the individual PR's.
Please let me know if anything needs to be changed!

**Comment by remyjette** [comment]
Thanks for taking care of it! Looks nice. Should be useful for students in upcoming semesters.

PRs merged. Marking this issue closed.

**Comment by genkimarshall** [comment]
Awesome! No problem :+1:
