### ISSUE TITLE
Clock setting

### ISSUE THREAD

**Issue by clarksmr** [cs3110/vagrant-opam#4]
The format string for the clock settings is wrong.  It has a lower case %m instead of an uppercase %M, which causes the clock to display the month instead of the minutes.

**Comment by remyjette** [comment]
Haha wow...I spent over an hour when building the VM wondering why the clock was a bit off - it wasn't stopped, just off by a few minutes. And the `date` command in the terminal was fine - ended up hoping it was an issue with the Guest Extensions in VirtualBox install and shipped it.

Fixed in cs3110/tools@ed17ca9c
